package com.example.periodsaathi.navigation

sealed class Screen(val route: String) {
    data object Splash : Screen("splash")
    data object Onboarding : Screen("onboarding")
    data object Login : Screen("login")
    data object NameSetup : Screen("name_setup")
    data object Home : Screen("home")
    data object Calendar : Screen("calendar")
    data object Wellness : Screen("wellness")
    data object PartnerMode : Screen("partner")
    data object Remedies : Screen("remedies")
    data object YogaFlow : Screen("yoga")
    data object Journal : Screen("journal")
    data object MoodMap : Screen("mood_map")
    data object Insights : Screen("insights")
    data object Settings : Screen("settings")
    data object ReportExport : Screen("report_export")
    data object TimeCapsule : Screen("time_capsule")
    data object Wardrobe : Screen("wardrobe")
    data object Challenges : Screen("challenges")
    data object BreathingMode : Screen("breathing")
    data object VoiceLog : Screen("voice_log")
    data object Profile : Screen("profile")
    data object More : Screen("more")
    data object Payment : Screen("payment")
}