package com.example.periodsaathi.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFFFFB5C8)
val PrimaryVariant = Color(0xFFFF8FAB)
val Secondary = Color(0xFFFFD1DC)
val Background = Color(0xFFFFF8F5)
val Surface = Color(0xFFFFF8F5)
val OnPrimary = Color(0xFFFFFFFF)
val OnSurface = Color(0xFF2D2D2D)
val OnSurfaceVariant = Color(0xFF6B6B6B)
val Error = Color(0xFFF44336)
val WarmCream = Color(0xFFFFF8F5)
val BlushPink = Color(0xFFFFB5C8)
val DeepRose = Color(0xFFFF8FAB)
val SoftLavender = Color(0xFFE8D5F5)
val Lavender = Color(0xFFE8D5F5)
val BabyBlue = Color(0xFFB5D8FF)
val ButterYellow = Color(0xFFFFF5B5)
val MintGreen = Color(0xFFB5FFCF)
val GlassWhite = Color(0x66FFFFFF)
val GlassBorder = Color(0x99FFFFFF)
val SoftCoral = Color(0xFFE8A0A0)
val Tertiary = Color(0xFF7C9DB5)
val PrimaryContainer = Color(0xFFF0E6E6)
val WarmGold = Color(0xFFFFD700)
