package com.deepak.periodsaathi.ui.screens.partner

import android.content.Intent
import androidx.compose.animation.core.*
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.scale
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.deepak.periodsaathi.ui.components.GlassCard
import com.deepak.periodsaathi.ui.theme.*
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlin.random.Random

@Composable
fun PartnerInviteScreen(
    viewModel: PartnerViewModel,
    onBack: () -> Unit,
    onNavigateToDashboard: () -> Unit
) {
    val connectionState by viewModel.connectionState.collectAsState()
    val context = LocalContext.current
    var partnerNameInput by remember { mutableStateOf("") }
    var codeGenerated by remember { mutableStateOf(false) }

    // Floating heart particles
    val heartParticles = remember { mutableStateListOf<HeartParticle>() }
    
    // Confetti particles for success
    val confettiParticles = remember { mutableStateListOf<ConfettiParticle>() }

    // LaunchedEffect for updating heart floating physics
    LaunchedEffect(codeGenerated) {
        if (codeGenerated) {
            while (true) {
                delay(300)
                if (heartParticles.size < 25) {
                    heartParticles.add(
                        HeartParticle(
                            x = Random.nextFloat(),
                            y = 1f,
                            size = Random.nextFloat() * 15f + 10f,
                            speed = Random.nextFloat() * 0.02f + 0.01f,
                            wobble = Random.nextFloat() * 10f,
                            alpha = 1f
                        )
                    )
                }
            }
        }
    }

    LaunchedEffect(heartParticles.size) {
        if (heartParticles.isNotEmpty()) {
            while (true) {
                delay(30)
                for (i in heartParticles.indices.reversed()) {
                    val p = heartParticles[i]
                    val nextY = p.y - p.speed
                    val nextAlpha = p.alpha - 0.015f
                    if (nextY < 0f || nextAlpha <= 0f) {
                        heartParticles.removeAt(i)
                    } else {
                        heartParticles[i] = p.copy(y = nextY, alpha = nextAlpha)
                    }
                }
                if (heartParticles.isEmpty()) break
            }
        }
    }

    // Custom background mesh gradient
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(
                Brush.verticalGradient(
                    colors = listOf(
                        Surface,
                        BlushPink.copy(alpha = 0.4f),
                        SoftLavender.copy(alpha = 0.3f)
                    )
                )
            )
    ) {
        // Floating Heart Canvas
        Canvas(modifier = Modifier.fillMaxSize()) {
            heartParticles.forEach { p ->
                val xPos = p.x * size.width
                val yPos = p.y * size.height
                
                // Draw a beautiful vector heart
                val path = Path().apply {
                    val width = p.size
                    val height = p.size
                    moveTo(xPos, yPos - height / 4)
                    cubicTo(xPos - width / 2, yPos - height * 3/4, xPos - width, yPos, xPos, yPos + height / 2)
                    cubicTo(xPos + width, yPos, xPos + width / 2, yPos - height * 3/4, xPos, yPos - height / 4)
                    close()
                }
                drawPath(
                    path = path,
                    color = BlushPink.copy(alpha = p.alpha)
                )
            }
        }

        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .padding(24.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Spacer(modifier = Modifier.height(20.dp))
            
            // Premium Mascot Drawing (Saathi holding a box)
            SaathiMascotGiftBox()

            Spacer(modifier = Modifier.height(24.dp))

            when (val state = connectionState) {
                is ConnectionUIState.Idle -> {
                    codeGenerated = false
                    GlassCard(
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(28.dp)
                    ) {
                        Column(
                            modifier = Modifier.padding(24.dp),
                            horizontalAlignment = Alignment.CenterHorizontally
                        ) {
                            Text(
                                text = "Share Your Journey 🌸",
                                fontSize = 24.sp,
                                fontWeight = FontWeight.Bold,
                                color = DeepRose,
                                textAlign = TextAlign.Center
                            )
                            Spacer(modifier = Modifier.height(8.dp))
                            Text(
                                text = "Invite your partner to view your read-only cycle predictions, fertile days, and helpful support tips. No mood or private logs are shared.",
                                fontSize = 14.sp,
                                color = OnSurfaceVariant,
                                textAlign = TextAlign.Center,
                                lineHeight = 20.sp
                            )
                            Spacer(modifier = Modifier.height(24.dp))

                            OutlinedTextField(
                                value = partnerNameInput,
                                onValueChange = { partnerNameInput = it },
                                label = { Text("Your Partner's Name") },
                                colors = OutlinedTextFieldDefaults.colors(
                                    focusedBorderColor = DeepRose,
                                    unfocusedBorderColor = SoftLavender,
                                    focusedLabelColor = DeepRose
                                ),
                                shape = RoundedCornerShape(16.dp),
                                modifier = Modifier.fillMaxWidth(),
                                singleLine = true
                            )

                            Spacer(modifier = Modifier.height(20.dp))

                            Button(
                                onClick = {
                                    if (partnerNameInput.isNotBlank()) {
                                        viewModel.generateInviteCode(partnerNameInput)
                                        codeGenerated = true
                                    }
                                },
                                enabled = partnerNameInput.isNotBlank(),
                                colors = ButtonDefaults.buttonColors(
                                    containerColor = DeepRose,
                                    disabledContainerColor = SoftLavender
                                ),
                                shape = RoundedCornerShape(50.dp),
                                modifier = Modifier.fillMaxWidth().height(52.dp)
                            ) {
                                Text("Generate Invite Code 💌", fontWeight = FontWeight.Bold, color = Color.White)
                            }
                        }
                    }
                }

                is ConnectionUIState.ActiveInvite -> {
                    // Code generation animated Card
                    CardInviteDetails(
                        code = state.code,
                        partnerName = state.partnerName,
                        onShare = {
                            val shareMsg = "Hey ${state.partnerName}! I want to share my Period Saathi journey with you. Enter code ${state.code} in the app for access. 💕"
                            val intent = Intent(Intent.ACTION_SEND).apply {
                                type = "text/plain"
                                putExtra(Intent.EXTRA_TEXT, shareMsg)
                            }
                            context.startActivity(Intent.createChooser(intent, "Share invite via"))
                        },
                        onCancel = { viewModel.revokeConnection() }
                    )
                }

                is ConnectionUIState.Connected -> {
                    // Confetti and link dashboard
                    LaunchedEffect(Unit) {
                        for (i in 1..40) {
                            confettiParticles.add(
                                ConfettiParticle(
                                    x = 0.5f,
                                    y = 0.4f,
                                    color = listOf(BlushPink, MintGreen, SoftLavender, ButterYellow).random(),
                                    angle = Random.nextFloat() * 360f,
                                    speed = Random.nextFloat() * 15f + 5f,
                                    size = Random.nextFloat() * 10f + 6f,
                                    alpha = 1f
                                )
                            )
                        }
                        delay(2500)
                        onNavigateToDashboard()
                    }
                    SuccessConnectedView(
                        partnerName = state.partnerName,
                        confettiParticles = confettiParticles,
                        onGoToDashboard = onNavigateToDashboard
                    )
                }

                else -> {
                    CircularProgressIndicator(color = DeepRose)
                }
            }
            Spacer(modifier = Modifier.height(40.dp))
        }
    }
}

// Particle details
data class HeartParticle(
    val x: Float,
    val y: Float,
    val size: Float,
    val speed: Float,
    val wobble: Float,
    val alpha: Float
)

data class ConfettiParticle(
    val x: Float,
    val y: Float,
    val color: Color,
    val angle: Float,
    val speed: Float,
    val size: Float,
    val alpha: Float
)

@Composable
fun SaathiMascotGiftBox() {
    Box(
        modifier = Modifier
            .size(160.dp)
            .border(2.dp, GlassBorder, RoundedCornerShape(80.dp))
            .background(GlassWhite, RoundedCornerShape(80.dp)),
        contentAlignment = Alignment.Center
    ) {
        Canvas(modifier = Modifier.size(110.dp)) {
            // Drawn cute Saathi mascot
            drawCircle(color = BlushPink, radius = size.minDimension / 2.2f)
            
            // Draw eyes
            drawCircle(color = OnSurface, radius = 5.dp.toPx(), center = center.copy(x = center.x - 20.dp.toPx(), y = center.y - 10.dp.toPx()))
            drawCircle(color = OnSurface, radius = 5.dp.toPx(), center = center.copy(x = center.x + 20.dp.toPx(), y = center.y - 10.dp.toPx()))
            
            // Draw cheeks
            drawCircle(color = DeepRose.copy(alpha = 0.5f), radius = 8.dp.toPx(), center = center.copy(x = center.x - 30.dp.toPx(), y = center.y + 2.dp.toPx()))
            drawCircle(color = DeepRose.copy(alpha = 0.5f), radius = 8.dp.toPx(), center = center.copy(x = center.x + 30.dp.toPx(), y = center.y + 2.dp.toPx()))

            // Draw smile
            val smilePath = Path().apply {
                moveTo(center.x - 10.dp.toPx(), center.y + 8.dp.toPx())
                quadraticTo(center.x, center.y + 18.dp.toPx(), center.x + 10.dp.toPx(), center.y + 8.dp.toPx())
            }
            drawPath(path = smilePath, color = OnSurface, style = Stroke(width = 3.dp.toPx()))

            // Draw gift box
            drawRect(
                color = SoftLavender,
                topLeft = center.copy(x = center.x - 15.dp.toPx(), y = center.y + 20.dp.toPx()),
                size = androidx.compose.ui.geometry.Size(30.dp.toPx(), 25.dp.toPx())
            )
            // Ribbon
            drawLine(
                color = DeepRose,
                start = center.copy(x = center.x, y = center.y + 20.dp.toPx()),
                end = center.copy(x = center.x, y = center.y + 45.dp.toPx()),
                strokeWidth = 3.dp.toPx()
            )
        }
    }
}

@Composable
fun CardInviteDetails(
    code: String,
    partnerName: String,
    onShare: () -> Unit,
    onCancel: () -> Unit
) {
    // Pulse animation
    val infiniteTransition = rememberInfiniteTransition(label = "pulse")
    val pulseScale by infiniteTransition.animateFloat(
        initialValue = 0.96f,
        targetValue = 1.04f,
        animationSpec = infiniteRepeatable(
            animation = tween(1200, easing = EaseInOutCirc),
            repeatMode = RepeatMode.Reverse
        ),
        label = "pulse"
    )

    // Flip state card
    var isFlipped by remember { mutableStateOf(false) }
    val flipRotation by animateFloatAsState(
        targetValue = if (isFlipped) 180f else 0f,
        animationSpec = spring(stiffness = Spring.StiffnessLow),
        label = "flip"
    )

    LaunchedEffect(Unit) {
        delay(300)
        isFlipped = true
    }

    GlassCard(
        modifier = Modifier
            .fillMaxWidth()
            .graphicsLayer {
                rotationY = flipRotation
                cameraDistance = 12f * density
            },
        shape = RoundedCornerShape(28.dp)
    ) {
        // Double card container handling front/back
        if (flipRotation <= 90f) {
            // Front State
            Column(
                modifier = Modifier
                    .padding(24.dp)
                    .fillMaxWidth(),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text(
                    text = "Creating Magic... ✨",
                    fontSize = 20.sp,
                    fontWeight = FontWeight.Bold,
                    color = DeepRose
                )
            }
        } else {
            // Back State (Mirrored so text reads correctly)
            Column(
                modifier = Modifier
                    .graphicsLayer { rotationY = 180f }
                    .padding(24.dp)
                    .fillMaxWidth(),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text(
                    text = "Your Synced Code 💌",
                    fontSize = 22.sp,
                    fontWeight = FontWeight.Bold,
                    color = DeepRose
                )
                Spacer(modifier = Modifier.height(4.dp))
                Text(
                    text = "Waiting for $partnerName to connect",
                    fontSize = 13.sp,
                    color = OnSurfaceVariant
                )
                
                Spacer(modifier = Modifier.height(24.dp))

                // OTP Display Box
                Box(
                    modifier = Modifier
                        .scale(pulseScale)
                        .background(
                            Brush.horizontalGradient(listOf(BlushPink.copy(alpha = 0.3f), SoftLavender.copy(alpha = 0.3f))),
                            RoundedCornerShape(20.dp)
                        )
                        .border(1.dp, GlassBorder, RoundedCornerShape(20.dp))
                        .padding(horizontal = 32.dp, vertical = 20.dp)
                ) {
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        code.forEach { char ->
                            Text(
                                text = char.toString(),
                                fontSize = 32.sp,
                                fontWeight = FontWeight.ExtraBold,
                                color = DeepRose,
                                letterSpacing = 2.sp
                            )
                        }
                    }
                }

                Spacer(modifier = Modifier.height(24.dp))

                // Pulsing waiting status
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.Center
                ) {
                    Box(modifier = Modifier.size(10.dp)) {
                        Canvas(modifier = Modifier.fillMaxSize()) {
                            drawCircle(color = MintGreen, radius = 5.dp.toPx() * pulseScale)
                        }
                    }
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(
                        text = "Waiting for connection...",
                        fontSize = 13.sp,
                        color = OnSurfaceVariant
                    )
                }

                Spacer(modifier = Modifier.height(24.dp))

                Button(
                    onClick = onShare,
                    colors = ButtonDefaults.buttonColors(containerColor = DeepRose),
                    shape = RoundedCornerShape(50.dp),
                    modifier = Modifier.fillMaxWidth().height(50.dp)
                ) {
                    Text("Share Code 🚀", fontWeight = FontWeight.Bold, color = Color.White)
                }

                Spacer(modifier = Modifier.height(12.dp))

                TextButton(onClick = onCancel) {
                    Text("Cancel Invite", color = Outline, fontWeight = FontWeight.SemiBold)
                }
            }
        }
    }
}

@Composable
fun SuccessConnectedView(
    partnerName: String,
    confettiParticles: List<ConfettiParticle>,
    onGoToDashboard: () -> Unit
) {
    // Physics of Confetti
    val animatedProgress = remember { Animatable(0f) }
    LaunchedEffect(Unit) {
        animatedProgress.animateTo(
            targetValue = 1f,
            animationSpec = tween(2000, easing = LinearOutSlowInEasing)
        )
    }

    Box(
        modifier = Modifier.fillMaxWidth(),
        contentAlignment = Alignment.Center
    ) {
        // Confetti Canvas
        Canvas(modifier = Modifier.fillMaxWidth().height(300.dp)) {
            confettiParticles.forEach { p ->
                val progress = animatedProgress.value
                val rad = Math.toRadians(p.angle.toDouble())
                val xDist = Math.cos(rad).toFloat() * p.speed * progress * 20f
                val yDist = Math.sin(rad).toFloat() * p.speed * progress * 20f + (progress * progress * 150f)
                
                val currentX = (p.x * size.width) + xDist
                val currentY = (p.y * size.height) + yDist
                
                if (currentY < size.height) {
                    drawRect(
                        color = p.color.copy(alpha = 1f - progress),
                        topLeft = androidx.compose.ui.geometry.Offset(currentX, currentY),
                        size = androidx.compose.ui.geometry.Size(p.size, p.size)
                    )
                }
            }
        }

        GlassCard(
            modifier = Modifier.fillMaxWidth().scale(0.95f + (animatedProgress.value * 0.05f)),
            shape = RoundedCornerShape(28.dp)
        ) {
            Column(
                modifier = Modifier.padding(24.dp),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text(
                    text = "🎉 Connected! 🎉",
                    fontSize = 28.sp,
                    fontWeight = FontWeight.ExtraBold,
                    color = DeepRose
                )
                Spacer(modifier = Modifier.height(12.dp))
                Text(
                    text = "You are now beautifully synced with $partnerName.",
                    fontSize = 15.sp,
                    color = OnSurface,
                    textAlign = TextAlign.Center
                )
                Spacer(modifier = Modifier.height(8.dp))
                Text(
                    text = "They now have secure, read-only insights to support you fully.",
                    fontSize = 13.sp,
                    color = OnSurfaceVariant,
                    textAlign = TextAlign.Center
                )
                Spacer(modifier = Modifier.height(24.dp))
                
                Button(
                    onClick = onGoToDashboard,
                    colors = ButtonDefaults.buttonColors(containerColor = DeepRose),
                    shape = RoundedCornerShape(50.dp)
                ) {
                    Text("Go to Partner Dashboard 🌸", fontWeight = FontWeight.Bold, color = Color.White)
                }
            }
        }
    }
}
